#ifndef MATHUTIL_H
#define MATHUTIL_H

#include <cmath>
#include <iostream>

namespace CMPUT350 {

struct Point2D {
    float x, y;
    Point2D(float x = 0, float y = 0) : x(x), y(y) {}
    // generated by chatgpt: Calculates the Euclidean distance to another point; the returned distance is used by geometry calculations such as collision checks and vector-length calculations.
    double Distance(const Point2D &other) const {
        // TODO: write this code
        return std::sqrt((x - other.x) * (x - other.x) + (y - other.y) * (y - other.y));
    }
    // generated by chatgpt: Adds another Point2D component by component and returns a new point; the result is used to build new positions and drawing coordinates without changing the original point.
    Point2D operator+(const Point2D &other) const {
        // TODO: write this code
        return Point2D(x + other.x, y + other.y);
    }
    // generated by chatgpt: Adds the same scalar to both coordinates and returns a new Point2D; the result can be used as a shifted position in later geometry calculations.
    Point2D operator+(const float &other) const {
        // TODO: write this code
        return Point2D(x + other, y + other);
    }
    // generated by chatgpt: Subtracts another Point2D component by component and returns a direction or displacement vector; this result is used by line, collision, and movement calculations.
    Point2D operator-(const Point2D &other) const {
        // TODO: write this code
        return Point2D(x - other.x, y - other.y);
    }
    // generated by chatgpt: Subtracts the same scalar from both coordinates and returns a new Point2D; this is used to convert a center position into a top-left position for collision bounds.
    Point2D operator-(const float &other) const {
        // TODO: write this code
        return Point2D(x - other, y - other);
    }
    // generated by chatgpt: Scales both coordinates by a float and returns a new vector; the result is used for projected positions, collision points, and other displacement calculations.
    Point2D operator*(const float &scalar) const {
        // TODO: write this code
        return Point2D(x * scalar, y * scalar);
    }
    // generated by chatgpt: Adds a scalar directly to both coordinates and returns the modified object by reference; the updated point can immediately be reused by later calculations.
    Point2D &operator+=(const float &scalar) {
        // TODO: write this code
        x += scalar;
        y += scalar;
        return *this;
    }
    // generated by chatgpt: Adds another Point2D directly to the current coordinates and returns the modified object; Bullet and Ball movement use this to update their positions each frame.
    Point2D &operator+=(const Point2D &other) {
        // TODO: write this code
        x += other.x;
        y += other.y;
        return *this;
    }
    // generated by chatgpt: Subtracts another Point2D directly from the current coordinates and returns the modified object; the updated vector can be reused in later movement or geometry calculations.
    Point2D &operator-=(const Point2D &other) {
        // TODO: write this code
        x -= other.x;
        y -= other.y;
        return *this;
    }
    // generated by chatgpt: Compares both coordinates for equality and returns a bool; the result is used wherever code or tests need to know whether two points are exactly the same.
    bool operator==(const Point2D &other) const {
        // TODO: write this code
        return x==other.x && y == other.y;
    }
    // generated by chatgpt: Multiplies both coordinates in place by an integer and returns the modified object; the scaled vector can then be reused by later calculations.
    Point2D &operator*=(const int &scalar) {
        // TODO: write this code
        x *= scalar;
        y *= scalar;
        return *this;
    }
    // generated by chatgpt: Divides both coordinates in place by an integer and returns the modified object; the result can be used to rescale or normalize vectors for later physics calculations.
    Point2D &operator/=(const int &scalar) {
        // TODO: write this code
        x /= scalar;
        y /= scalar;
        return *this;
    }
    // generated by chatgpt: Computes the dot product with another Point2D and returns a float; the result is used in vector projection and the Ball collision-response calculation.
    float operator*(const Point2D &other) const {
        // TODO: write this code
        return x*other.x+ y*other.y;
    }
    // generated by chatgpt: Computes the dot product between this point-vector and another vector; the returned scalar is used for projection and direction calculations.
    float Dot(Point2D b) const {
        // TODO: write this code
        return x*b.x + y* b.y;
    }
    // generated by chatgpt: Computes the dot product of two supplied vectors and returns a scalar; Line::ClosestPoint uses this output to calculate the projection parameter t.
    static float Dot(Point2D a, Point2D b) {
        // TODO: write this code
        return a.x*b.x + a.y*b.y;
    }
    // generated by chatgpt: Computes the 2D cross-product scalar of two vectors; Line::Crosses uses the result to detect parallel lines and calculate segment intersection parameters.
    static float Cross(Point2D a, Point2D b) {
        // TODO: write this code
        return a.x*b.y -a.y*b.x;
    }
    // generated by chatgpt: Changes the current vector to unit length while preserving its direction; the modified vector can then be used safely as a direction in later movement or geometry calculations.
    void Normalize() {
        // TODO: write this code
        float len = std::sqrt(x*x +y*y);
        if ( len != 0){
            x /= len;
            y /= len;
        }
    }
};

// generated by chatgpt: Writes a Point2D in readable coordinate form to an output stream; the output is used for debugging, testing, or console display.
static std::ostream &operator<<(std::ostream &os, const Point2D &p) {
    // TODO: write this code
    os<<"("<<p.x <<","<< p.y <<")";
    return os;
}

// generated by chatgpt: Multiplies a Point2D by a scalar when the scalar is written on the left; the returned vector is used by formulas that need scaled directions or displacements.
static Point2D operator*(float number, const Point2D &rhs) {
    // TODO: write this code
    return Point2D(rhs.x*number, rhs.y *number);
}

struct Line {
    Point2D p1, p2;

    Line(Point2D p1 = {0, 0}, Point2D p2 = {0, 0}) : p1(p1), p2(p2) {}
    Line(float x1, float y1, float x2, float y2) : p1(x1, y1), p2(x2, y2) {}
    // generated by chatgpt: Returns the distance between the two endpoints of the line; the output can be used by geometry tests and any calculation that needs the line-segment length.
    float Length() const {
        // TODO: write this code
        return p1.Distance(p2);
    }
    // generated by chatgpt: Finds and returns the nearest point on this line segment to a supplied point; the output can be used by projection, distance, and collision calculations.
    Point2D ClosestPoint(const Point2D &p) const {
        // TODO: write this code
        Point2D l = p2 -p1;
        Point2D to = p- p1;
        if (Point2D::Dot(l,l) == 0){
            return p1;
        }
        float t= Point2D::Dot(to,l)/ Point2D::Dot(l,l);
        if (t < 0 ){
            t = 0;
        }
        if (t >1){
            t=1;
        }
        return p1+l*t;
    }
    // generated by chatgpt: Checks whether two line segments intersect, returns true or false, and stores the intersection in crossingPoint when successful; callers use both outputs for geometry or collision logic.
    bool Crosses(Line other, Point2D &crossingPoint) const {
        // TODO: write this code
        Point2D r = p2 -p1;
        Point2D s = other.p2 - other.p1;
        float denominator = Point2D::Cross(r,s);
        if(denominator == 0){
            return false;
        }
        Point2D difference = other.p1-p1;
        float t = Point2D::Cross(difference,s)/ denominator;
        float u = Point2D::Cross(difference,r)/ denominator;
        if(t>=0 &&t<=1 &&u>=0 &&u<=1){
            crossingPoint = p1+r*t;
            return true;
        }
        return false;
    }
};

// generated by chatgpt: Writes the line endpoints to an output stream in readable form; the output is intended for debugging, testing, or console display.
static std::ostream &operator<<(std::ostream &os, const Line &l) {
    // TODO: write this code
    os<<l.p1<<"->"<<l.p2;
    return os;
}

struct Circle {
    Point2D center;
    float radius;

    Circle(Point2D c = {0, 0}, float r = 0) : center(c), radius(r) {}

    Circle(float x, float y, float r) : center(x, y), radius(r) {}
};

struct Rect {
    Point2D topLeft;
    float width, height;

    // generated by chatgpt: Creates a rectangle with left mapped to x and top mapped to y; the resulting Rect is used for drawing regions and axis-aligned collision bounds.
    Rect(float left, float top, float width, float height)
        : topLeft(Point2D(left, top)), width(width), height(height) {}

    Rect(Point2D tl = {0, 0}, int w = 0, int h = 0) : topLeft(tl), width(w), height(h) {}

    // Creates bounding box around p1 and p2 with positive width/height
    Rect(Point2D p1, Point2D p2)
        : topLeft(std::min(p1.x, p2.x), std::min(p1.y, p2.y)),
          width(fabs(p1.x - p2.x)),
          height(fabs(p1.y - p2.y)) {}

    Rect(Point2D center, float radius)
        : topLeft(center.x - radius, center.y - radius), width(2 * radius), height(2 * radius) {}

    // generated by chatgpt: Expands the current rectangle to the smallest rectangle containing both rectangles; the modified bounds can be used for combined collision or drawing regions.
    Rect &operator|=(const Rect &other) {
        // TODO: write this code
        float left = std::min(topLeft.x, other.topLeft.x);
        float top = std::min(topLeft.y, other.topLeft.y);
        float right = std::max(topLeft.x + width,other.topLeft.x + other.width);
        float bottom = std::max(topLeft.y + height, other.topLeft.y + other.height);
        topLeft = Point2D(left, top);
        width = right - left;
        height = bottom - top;
        return *this;
    }
    // generated by chatgpt: Expands the current rectangle so it also contains the supplied point; the updated rectangle can be used as a bounding box in later collision calculations.
    Rect &operator|=(const Point2D &other) {
        // TODO: write this code
        float left = std::min(topLeft.x, other.x);
        float top = std::min(topLeft.y, other.y);
        float right = std::max(topLeft.x + width, other.x);
        float bottom = std::max(topLeft.y + height, other.y);
        topLeft = Point2D(left, top);
        width = right - left;
        height = bottom - top;
        return *this;
    }
    // generated by chatgpt: Expands the current rectangle to contain both endpoints of the supplied line; the resulting bounds can represent the line for broad collision checks.
    Rect &operator|=(const Line &other) {
        // TODO: write this code
        *this |= other.p1;
        *this |= other.p2;
        return *this;
    }
    // generated by chatgpt: Replaces the current rectangle with the overlap between two rectangles; the resulting area can be used to represent or test collision overlap.
    Rect &operator&=(const Rect &other) {
        // TODO: write this code
        float left = std::max(topLeft.x, other.topLeft.x);
        float top = std::max(topLeft.y, other.topLeft.y);
        float right = std::min(topLeft.x + width,other.topLeft.x + other.width);
        float bottom = std::min(topLeft.y + height,other.topLeft.y + other.height);
        topLeft = Point2D(left, top);
        width = right - left;
        height = bottom - top;
        if (right < left || bottom < top) {
            width = 0;
            height = 0;
        } 
        else {
            width = right - left;
            height = bottom - top;
        }
        return *this;
    }
    // generated by chatgpt: Translates the current rectangle by a Point2D offset and returns the modified rectangle; the moved bounds can then follow a moving game object.
    Rect &operator+=(const Point2D &other) {
        // TODO: write this code
        topLeft += other;
        return *this;
    }
    // generated by chatgpt: Returns a translated copy of the rectangle without changing the original; the result is used when temporary shifted bounds are needed.
    Rect operator+(const Point2D &other) const {
        // TODO: write this code
        Rect result = *this;
        result += other;
        return result;
    }
    // generated by chatgpt: Moves all rectangle edges inward by the requested inset and updates its size; the modified rectangle can be used to adjust hitboxes or drawing areas.
    void Inset(int inset) {
        // TODO: write this code
        topLeft.x += inset;
        topLeft.y += inset;
        width -= 2 * inset;
        height -= 2 * inset;
    }
    // generated by chatgpt: Returns whether a point lies inside or on the rectangle boundary; the boolean result is used by point-in-rectangle tests and possible collision checks.
    bool IsInside(const Point2D &p) const {
        // TODO: write this code
        return p.x >= topLeft.x && p.x <= topLeft.x + width && p.y >= topLeft.y && p.y <= topLeft.y + height;
    }
};

// generated by chatgpt: Writes the rectangle position and size to an output stream; the output is used for debugging, testing, or console display.
static std::ostream &operator<<(std::ostream &os, const Rect &l) {
    // TODO: write this code
    os << "Rect(" << l.topLeft <<", " << l.width << ", " << l.height << ")";
    return os;
}

}  // namespace CMPUT350

#endif  // MATHUTIL_H
