#include "Bullet.h"
#include "Player.h"
// generated by chatgpt: Initializes the bullet position, previous position, movement heading, owner flag, alive state, and starting bounds so later update, rendering, and collision functions have the state they need.
Bullet::Bullet(CMPUT350::Point2D location, CMPUT350::Point2D heading, bool player):
mLocation(location), mPreviousLocation(location),
mHeading(heading),mPlayer(player),
mAlive(true), mBounds(location, location)
{
}

// generated by chatgpt: Returns whether this bullet was fired by the player; Enemy and Player collision logic use this output to decide whether the collision should kill or be ignored.
bool Bullet::IsPlayerBullet()
{
    // TODO: Update
    return mPlayer;
}

// generated by chatgpt: Provides the GameObject initialization hook for Bullet; no extra setup is required because the constructor already initializes the bullet state.
void Bullet::Initialize(CMPUT350::GameContext* context)
{
}

// generated by chatgpt: Saves the previous position, moves the bullet by its heading, rebuilds its movement bounds, and kills it when it leaves the window; the updated state is used by rendering, collision detection, and object cleanup.
void Bullet::Update(CMPUT350::GameContext* context)
{
    mPreviousLocation = mLocation;
    mLocation += mHeading;
    mBounds = CMPUT350::Rect(mPreviousLocation, mLocation);
    //if bullet is out of screen, kill it
    if (mLocation.x < 0 ||
        mLocation.x > context->ScreenContext->GetWindowWidth() ||
        mLocation.y < 0 ||
        mLocation.y > context->ScreenContext->GetWindowHeight())
    {
        Kill();
    }
}

// generated by chatgpt: Provides the late-update hook for Bullet; no extra late-frame state changes are currently required.
void Bullet::LateUpdate(CMPUT350::GameContext* context)
{
}

// generated by chatgpt: Indicates that Bullet does not handle keyboard input by returning false; the engine uses this result while dispatching key events.
bool Bullet::HandleKeyEvent(CMPUT350::GameContext* context, char key)
{
    return false;
}

// generated by chatgpt: Provides the background-rendering hook for Bullet; no background drawing is needed because the bullet is drawn in the foreground pass.
void Bullet::RenderBackground(CMPUT350::GameContext* context)
{
}

// generated by chatgpt: Draws the bullet as a line from its previous position to its current position; the visible output is rendered by DrawContext during the foreground pass.
void Bullet::RenderForeground(CMPUT350::GameContext* context)
{
    context->ScreenContext->DrawLine( mPreviousLocation, mLocation, 2.0f, CMPUT350::Colors::white );
}

// generated by chatgpt: Handles a bullet collision by ignoring the player's own bullet hitting the player and killing the bullet for other collisions; the alive state is later consumed by GameEngine object cleanup.
void Bullet::CollisionEnter(const std::shared_ptr<CMPUT350::CollisionObject>& obj)
{
    std::shared_ptr<Player> player = std::dynamic_pointer_cast<Player>(obj);
    if (mPlayer && player){
        return;
    }
    Kill();
}

// generated by chatgpt: Marks the bullet as dead by setting mAlive to false; GameEngine later uses IsAlive to remove the bullet from active objects.
void Bullet::Kill()
{
    mAlive = false;
}

// generated by chatgpt: Returns the current bullet alive state; GameEngine uses this output to decide whether the bullet remains active or should be removed.
bool Bullet::IsAlive() const
{
    // TODO: Update code
    return mAlive;
}

// generated by chatgpt: Returns the bullet's current collision rectangle; the collision-processing stage uses this output to test the bullet against other CollisionObjects.
const CMPUT350::Rect& Bullet::GetBounds()
{
    // TODO: Update code
    return mBounds;
}
