#include "Enemy.h"
#include "Bullet.h"

// generated by chatgpt: Initializes the enemy position, 40 by 40 collision bounds, and alive state so rendering and collision logic can use the stored enemy state.
Enemy::Enemy(CMPUT350::Point2D loc)
{
    // TODO: Update code
    mLocation = loc;
    mBounds = CMPUT350::Rect(loc - 20.0f, 40, 40);
    mAlive = true;
}

// generated by chatgpt: Provides the GameObject initialization hook for Enemy; no additional setup is currently required because the constructor initializes its state.
void Enemy::Initialize(CMPUT350::GameContext* context)
{
}

// generated by chatgpt: Leaves the enemy position unchanged each frame because the basic Enemy is stationary; later rendering and collision checks therefore use the same location.
void Enemy::Update(CMPUT350::GameContext* context)
{
}

// generated by chatgpt: Provides the late-update hook for Enemy; no additional state changes are currently required after collision processing.
void Enemy::LateUpdate(CMPUT350::GameContext* context)
{
}

// generated by chatgpt: Returns false because Enemy does not respond to keyboard input; the engine uses this result while dispatching input events.
bool Enemy::HandleKeyEvent(CMPUT350::GameContext* context, char key)
{
    return false;
}

// generated by chatgpt: Provides the background-rendering hook for Enemy; no background drawing is needed because the enemy is drawn in the foreground pass.
void Enemy::RenderBackground(CMPUT350::GameContext* context)
{
}

// generated by chatgpt: Draws the enemy using its collision rectangle; the resulting red rectangle is displayed by DrawContext during the foreground render pass.
void Enemy::RenderForeground(CMPUT350::GameContext* context)
{
    context->ScreenContext->DrawRect( mBounds,CMPUT350::Colors::red);
}

// generated by chatgpt: Checks whether the colliding object is a player-fired Bullet and kills the enemy when that condition is true; the changed alive state is later used by GameEngine cleanup.
void Enemy::CollisionEnter(const std::shared_ptr<CMPUT350::CollisionObject>& obj)
{
    std::shared_ptr<Bullet> bullet = std::dynamic_pointer_cast<Bullet>(obj);
    if (bullet && bullet->IsPlayerBullet())
    {
        Kill();
    }
}

// generated by chatgpt: Marks the enemy as dead by setting mAlive to false; GameEngine later uses IsAlive to remove the enemy from active objects.
void Enemy::Kill()
{
    mAlive = false;
}

// generated by chatgpt: Returns the enemy's current alive state; GameEngine uses this output to decide whether the enemy should stay active or be removed.
bool Enemy::IsAlive() const
{
    // TODO: Update code
    return mAlive;;
}

// generated by chatgpt: Returns the enemy's collision rectangle; the collision-processing stage uses this output when checking overlap with bullets and other CollisionObjects.
const CMPUT350::Rect& Enemy::GetBounds()
{
    // TODO: Update code
    return mBounds;
}
