#include <cassert>
#include "Player.h"
#include "Bullet.h"
#include "GameContext.h"
#include <algorithm>
#include <SFML/Window/Keyboard.hpp>

// generated by chatgpt: Initializes the player's position, 40 by 40 collision bounds, and alive state so movement, rendering, firing, and collision logic can use the same stored state.
Player::Player(CMPUT350::Point2D loc)
:mLocation(loc), mBounds(loc - 20.0f, 40, 40),mAlive(true)
{
    // TODO: Update code
}

// generated by chatgpt: Provides the GameObject initialization hook for Player; no additional setup is currently needed because the constructor initializes the player state.
void Player::Initialize(CMPUT350::GameContext* context)
{
}

// generated by chatgpt: Checks A and D every frame, moves the player continuously, clamps the player inside the window, and refreshes the collision bounds; the updated position is then used by rendering and collision processing.
void Player::Update(CMPUT350::GameContext* context)
{
    const float speed = 10.0f;
    const float halfWidth = 20.0f;

    if (sf::Keyboard::isKeyPressed(sf::Keyboard::Key::A)){
        mLocation.x -= speed;
    }

    if (sf::Keyboard::isKeyPressed(sf::Keyboard::Key::D)){
        mLocation.x += speed;
    }

    // Do not allow the player to leave the screen
    float screenWidth = context->ScreenContext->GetWindowWidth();
    if (mLocation.x < halfWidth){
        mLocation.x = halfWidth;
    }
    if (mLocation.x > screenWidth - halfWidth){
        mLocation.x = screenWidth - halfWidth;
    }
    mBounds = CMPUT350::Rect(mLocation- 20.0f,40,40);
}

// generated by chatgpt: Provides the late-update hook for Player; no additional state changes are currently required after collision processing.
void Player::LateUpdate(CMPUT350::GameContext* context)
{
}

// generated by chatgpt: Handles Space as a firing event, removes expired bullet references, enforces the two-active-bullet limit, creates a new Bullet through EngineView, and returns whether the key was handled.
bool Player::HandleKeyEvent(CMPUT350::GameContext* context, char key)
{
    if (key == ' ')
    {
        mBullets.erase(
            std::remove_if(
                mBullets.begin(),
                mBullets.end(),
                [](const std::weak_ptr<Bullet>& bullet)
                {
                    return bullet.expired();
                }
            ),
            mBullets.end()
        );

        if (mBullets.size() >= 2)
        {
            return true;
        }

        std::shared_ptr<Bullet> bullet =
            std::make_shared<Bullet>(
                mLocation,
                CMPUT350::Point2D(0, -15),
                true
            );

        context->mEngineView->AddGameObject(bullet);
        mBullets.push_back(bullet);
        return true;
    }
    return false;
}

// generated by chatgpt: Provides the background-rendering hook for Player; no background drawing is needed because the ship is drawn in the foreground pass.
void Player::RenderBackground(CMPUT350::GameContext* context)
{
}

// generated by chatgpt: Calculates three ship vertices around the current player position and draws the triangular ship; the visible output is rendered on screen by DrawContext.
void Player::RenderForeground(CMPUT350::GameContext* context)
{
    CMPUT350::Point2D top =  mLocation + CMPUT350::Point2D(0, -20);
    CMPUT350::Point2D left = mLocation + CMPUT350::Point2D(-20, 20);
    CMPUT350::Point2D right = mLocation + CMPUT350::Point2D(20, 20);
    context->ScreenContext->DrawLine( top,left,3.0f,CMPUT350::Colors::cyan);

    context->ScreenContext->DrawLine(left,right,3.0f,CMPUT350::Colors::cyan);

    context->ScreenContext->DrawLine(right,top,3.0f,CMPUT350::Colors::cyan);
}

// generated by chatgpt: Checks whether the colliding object is a player-fired Bullet and ignores that collision so the player's own projectile does not affect the player.
void Player::CollisionEnter(const std::shared_ptr<CMPUT350::CollisionObject>& obj)
{
    std::shared_ptr<Bullet> bullet =std::dynamic_pointer_cast<Bullet>(obj);
    if (bullet && bullet->IsPlayerBullet()){
        return;
    }
}

// generated by chatgpt: Marks the player as dead by setting mAlive to false; GameEngine can later use IsAlive to decide whether the player should remain active.
void Player::Kill()
{
    mAlive = false;
}

// generated by chatgpt: Returns the player's current alive state; GameEngine uses this output during dead-object cleanup.
bool Player::IsAlive() const
{
    // TODO: Update code
    return mAlive;
}

// generated by chatgpt: Returns the player's current collision rectangle; the collision-processing stage uses this output to test overlap with other CollisionObjects.
const CMPUT350::Rect& Player::GetBounds()
{
    // TODO: Update code
    return mBounds;
}
